
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: lab2-middlewares
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        env:
        - name: REDIS_PASSWORD
          value: "5iwrnpFC4BRqADn6qCFV"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ""
      resources:
        requests:
          storage: 5Gi
